### ISSUE TITLE
How do you compute q(z| x, y) at test time?

### ISSUE THREAD

**Issue by hoangcuong2011** [DeepLearnXMU/VNMT#3]
Hello,

I am reading your paper Variational Neural Machine Translation.

The paper is great! I was wondering one thing: How do you compute q(z| x, y) at test time? 
I cannot find an obvious approach to this as at test time we don't have y to compute their representation and then q(z| x, y).

Thanks!

Best,

**Comment by bzhangGo** [comment]
Hi @hoangcuong2011,

There are different approaches to approximately solve this problem. In our paper, during test time, we use **p(z|x; \theta)** as the alternative to q(z|x, y; \phi) due to the unavaliability of y. The intuition behind is that at training phase, the optimization of lower bound objective enforces the similarity of p(z|x; \theta) and q(z|x, y; \phi) via KL divergence. In other words, we believe that the high-capability neural networks can distill knowledge from q(z|x, y; \phi) to p(z|x; \theta).

Of course, this is not the only solution. To my knowledge, there are some MCMC methods that iteratively generate y using both p(z|x; \theta) and q(z|x, y; \phi) to better approximate the true posterior q(z|x, y).

**Comment by AgoloCuongHoang** [comment]
Hi,

Thank you. It makes sense!

**Comment by hoangcuong2011** [comment]
Hi,

Thank you. It makes sense!
